[package]
name = "grpc-sum"
version = "0.1.0"
edition = "2021"

[dependencies]
async-stream = "0.3.2"
futures = "0.3"
prost = "0.9"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
tokio-stream = "0.1.8"
tonic = "0.6.2"

[build-dependencies]
tonic-build = "0.6"
