[package]
name = "grpc-sum"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3"
prost = "0.9"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
tonic = "0.6.1"

[build-dependencies]
tonic-build = "0.6"
